"""Added ps_dwhr_demo_addr-related mds_person_preferred_name table.

Revision ID: 005be5bae19e
Revises: 3aff4674ce03
Create Date: 2017-03-06 15:15:26.186434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005be5bae19e'
down_revision = '3aff4674ce03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mds_person_preferred_name',
    sa.Column('preferred_name', sa.String(length=50), nullable=False),
    sa.Column('emplid', sa.String(length=11), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emplid'], ['mds_person.emplid'], ),
    sa.PrimaryKeyConstraint('preferred_name', 'emplid', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mds_person_preferred_name')
    # ### end Alembic commands ###
