"""Creates a umn_person table.

Revision ID: 1e930c89445b
Revises: 88c66a1c82b5
Create Date: 2017-12-12 15:38:05.671339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '1e930c89445b'
down_revision = '88c66a1c82b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umn_person',
    sa.Column('emplid', sa.String(length=11), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('emplid', 'timestamp')
    )
    op.drop_table('emplid_personid_xref')
    op.drop_table('all_jobs_previous')
    op.drop_table('schema_migrations')
    op.drop_table('affiliate_departments')
    op.drop_table('contract_projectid_xref')
    op.drop_table('deptid_orgid_xref')
    op.drop_table('job_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_codes',
    sa.Column('id', oracle.NUMBER(precision=38, scale=0, asdecimal=False), nullable=False),
    sa.Column('jobcode', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pool', sa.VARCHAR(length=255), nullable=True),
    sa.Column('descr', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', oracle.DATE(), nullable=False),
    sa.Column('updated_at', oracle.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='sys_c00331518')
    )
    op.create_table('deptid_orgid_xref',
    sa.Column('deptid', sa.VARCHAR(length=8), nullable=False),
    sa.Column('orgid', sa.VARCHAR(length=18), nullable=False),
    sa.Column('descr', sa.VARCHAR(length=60), nullable=True)
    )
    op.create_table('contract_projectid_xref',
    sa.Column('contract_num', sa.VARCHAR(length=25), nullable=False),
    sa.Column('buiness_unit_pc', sa.VARCHAR(length=5), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=15), nullable=True)
    )
    op.create_table('affiliate_departments',
    sa.Column('id', oracle.NUMBER(precision=38, scale=0, asdecimal=False), nullable=False),
    sa.Column('deptid', sa.VARCHAR(length=255), nullable=True),
    sa.Column('descr', sa.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', oracle.DATE(), nullable=False),
    sa.Column('updated_at', oracle.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='sys_c00331522')
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=255), nullable=False)
    )
    op.create_table('all_jobs_previous',
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=True),
    sa.Column('empl_rcdno', sa.VARCHAR(length=40), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('jobcode', sa.VARCHAR(length=6), nullable=True),
    sa.Column('jobcode_descr', sa.VARCHAR(length=35), nullable=True),
    sa.Column('job_indicator', sa.VARCHAR(length=40), nullable=True),
    sa.Column('empl_status', sa.VARCHAR(length=4), nullable=True),
    sa.Column('paygroup', sa.VARCHAR(length=12), nullable=True),
    sa.Column('deptid', sa.VARCHAR(length=10), nullable=True),
    sa.Column('deptid_descr', sa.VARCHAR(length=30), nullable=True),
    sa.Column('um_jobcode_group', sa.VARCHAR(length=8), nullable=True),
    sa.Column('um_college', sa.VARCHAR(length=20), nullable=True),
    sa.Column('um_college_descr', sa.VARCHAR(length=30), nullable=True),
    sa.Column('campus', sa.VARCHAR(length=20), nullable=True),
    sa.Column('um_zdeptid', sa.VARCHAR(length=80), nullable=True),
    sa.Column('um_zdeptid_descr', sa.VARCHAR(length=30), nullable=True),
    sa.Column('status_flg', sa.VARCHAR(length=1), nullable=True),
    sa.Column('record_source', sa.CHAR(length=1), nullable=True),
    sa.Column('job_entry_dt', oracle.DATE(), nullable=True),
    sa.Column('position_entry_dt', oracle.DATE(), nullable=True),
    sa.Column('calculated_start_dt', oracle.DATE(), nullable=True)
    )
    op.create_table('emplid_personid_xref',
    sa.Column('emplid', sa.VARCHAR(length=12), nullable=False),
    sa.Column('personid', sa.VARCHAR(length=12), nullable=False),
    sa.Column('orgid', sa.VARCHAR(length=18), nullable=False)
    )
    op.drop_table('umn_person')
    # ### end Alembic commands ###
