"""Corrected the spelling of instl_email_addr to be consistent with ps_dwhr_demo_addr.

Revision ID: 96024695ebd1
Revises: 005be5bae19e
Create Date: 2017-03-06 16:14:06.845171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '96024695ebd1'
down_revision = '005be5bae19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mds_person_instl_email_addr',
    sa.Column('instl_email_addr', sa.String(length=15), nullable=False),
    sa.Column('emplid', sa.String(length=11), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emplid'], ['mds_person.emplid'], ),
    sa.PrimaryKeyConstraint('instl_email_addr', 'emplid', 'timestamp')
    )
    op.drop_table('mds_person_inst_email_addr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mds_person_inst_email_addr',
    sa.Column('inst_email_addr', sa.VARCHAR(length=15), nullable=False),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('timestamp', oracle.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['emplid'], ['mds_person.emplid'], name='SYS_C00263164'),
    sa.PrimaryKeyConstraint('inst_email_addr', 'emplid', 'timestamp', name='sys_c00263163')
    )
    op.drop_table('mds_person_instl_email_addr')
    # ### end Alembic commands ###
