grant select on person to oit_expert_rd_all;
grant select on pure_org to oit_expert_rd_all;
grant select on pure_internal_org to oit_expert_rd_all;
grant select on research_output to oit_expert_rd_all;
select * from pure_internal_org where lft >= 505 and rgt <= 520;
select * from pure_internal_org where "level" > 3;
select count(*) from pure_org;
select * from pure_internal_org where pure_id = 'LKTQDNVXHPZC';
select * from pure_internal_org where pure_id = 'MNDRIVE';
select * from pure_org where pure_id in ('ZNVNNMA','NNIWQIQRQ');
select * from pure_internal_org where pure_id in ('ZNVNNMA','NNIWQIQRQ');
select * from pure_org where name_en = 'Minnesota Agriculture Experiment Station';
select * from pure_internal_org where pure_uuid = 'a6bfaa1e-53d6-49ae-952b-62b78aef7c70';
select * from pure_org where pure_id is null;
select * from pure_org po left outer join pure_internal_org pio on po.pure_uuid = pio.pure_uuid;
select pure_uuid, count(*) from pure_internal_org group by pure_uuid having count(*) > 1;
select * from pure_internal_org where pure_uuid is null;
