"""Renames an index to use sqlalchemy naming conventions.

Revision ID: 1fdd6c1c321e
Revises: 9f7b8eb604d6
Create Date: 2020-10-15 15:47:19.131145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdd6c1c321e'
down_revision = '9f7b8eb604d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_author_collaboratio_6a25', table_name='author_collaboration')
    op.create_index(op.f('ix_author_collaboration_pure_uuid'), 'author_collaboration', ['pure_uuid'], unique=False)


def downgrade():
    op.drop_index(op.f('ix_author_collaboration_pure_uuid'), table_name='author_collaboration')
    op.create_index('ix_author_collaboratio_6a25', 'author_collaboration', ['pure_uuid'], unique=False)
