"""Added a not null constraint to person.timestamp.

Revision ID: 2fd08e3d1ff0
Revises: f486afeae516
Create Date: 2017-02-14 14:50:35.277205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '2fd08e3d1ff0'
down_revision = 'f486afeae516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'timestamp',
               existing_type=oracle.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'timestamp',
               existing_type=oracle.DATE(),
               nullable=True)
    # ### end Alembic commands ###
