"""Removes pure_json*516 tables.

Revision ID: 5ef0b3a6aebf
Revises: 3a57965067e9
Create Date: 2021-06-10 15:45:00.336186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '5ef0b3a6aebf'
down_revision = '3a57965067e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pure_json_external_organisation_516')
    op.drop_table('pure_json_research_output_516')
    op.drop_table('pure_json_person_516_staging')
    op.drop_table('pure_json_change_516')
    op.drop_table('pure_json_person_516')
    op.drop_table('pure_json_external_organisation_516_staging')
    op.drop_table('pure_json_organisation_516')
    op.drop_table('pure_json_change_516_history')
    op.drop_table('pure_json_research_output_516_staging')
    op.drop_table('pure_json_organisation_516_staging')
    op.drop_table('pure_json_external_person_516_staging')
    op.drop_table('pure_json_external_person_516')

def downgrade():
    op.create_table('pure_json_external_person_516',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_external_person_516_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_external_person_516')
    )
    op.create_table('pure_json_external_person_516_staging',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_external_person_516_staging_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_external_person_516_staging')
    )
    op.create_table('pure_json_organisation_516_staging',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_organisation_516_staging_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_organisation_516_staging')
    )
    op.create_table('pure_json_research_output_516_staging',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_research_output_516_staging_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_research_output_516_staging')
    )
    op.create_table('pure_json_change_516_history',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('family_system_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('pure_version', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', 'pure_version', name='pk_pure_json_change_516_history')
    )
    op.create_table('pure_json_organisation_516',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_organisation_516_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_organisation_516')
    )
    op.create_table('pure_json_external_organisation_516_staging',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_external_organisation_516_staging_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_external_organisation_516_staging')
    )
    op.create_table('pure_json_person_516',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_person_516_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_person_516')
    )
    op.create_table('pure_json_change_516',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('family_system_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('pure_version', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_change_516_json_document'),
    sa.PrimaryKeyConstraint('uuid', 'pure_version', name='pk_pure_json_change_516')
    )
    op.create_table('pure_json_person_516_staging',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_person_516_staging_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_person_516_staging')
    )
    op.create_table('pure_json_research_output_516',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_research_output_516_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_research_output_516')
    )
    op.create_table('pure_json_external_organisation_516',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_external_organisation_516_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_external_organisation_516')
    )
