"""Recreates pure_sync_award_*_holder tables, adding role to the PKs, and some dates to internal holders

Revision ID: 64b526f5d4b0
Revises: 71c220afd21f
Create Date: 2026-03-27 09:38:33.149884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '64b526f5d4b0'
down_revision = '71c220afd21f'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('pure_sync_award_internal_holder',
    sa.Column('award_id', sa.String(length=15), nullable=False),
    sa.Column('person_id', sa.String(length=1024), nullable=False),
    sa.Column('emplid', sa.String(length=11), nullable=False),
    sa.Column('organisation_id', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('association_start_date', sa.DateTime(), nullable=True),
    sa.Column('association_end_date', sa.DateTime(), nullable=True),
    sa.Column('inserted', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['pure_sync_award.award_id'], name=op.f('fk_pure_sync_award_internal_holder_award_id_pure_sync_award')),
    sa.ForeignKeyConstraint(['person_id'], ['pure_sync_person_data.person_id'], name=op.f('fk_pure_sync_award_internal_holder_person_id_pure_sync_person_data')),
    sa.PrimaryKeyConstraint('award_id', 'person_id', 'role', name=op.f('pk_pure_sync_award_internal_holder'))
    )
    op.create_index(op.f('ix_pure_sync_award_internal_holder_emplid'), 'pure_sync_award_internal_holder', ['emplid'], unique=False)
    op.alter_column('pure_sync_award_external_holder', 'role',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=15),
               existing_nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('umn_person_pure_org', 'job_description',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False,
               existing_comment='The description of this job in PeopleSoft. Maybe be better to use a job code here instead.')
    op.alter_column('pure_sync_award_external_holder', 'role',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.alter_column('pure_json_collection_meta', 'api_version',
               existing_type=sa.VARCHAR(length=15),
               comment='The Pure API version, without the decimal point, i.e., 516 for version 5.16.',
               existing_comment='The Pure API version, without the decimal point, i.e., 518 for version 5.18.',
               existing_nullable=False)
    op.add_column('pure_json_change_524_history', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_524', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_523_history', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_523', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_518_history', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_518', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_517_history', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.add_column('pure_json_change_517', sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
    op.drop_index(op.f('ix_pure_internal_org_rgt'), table_name='pure_internal_org')
    op.drop_index(op.f('ix_pure_internal_org_lft'), table_name='pure_internal_org')
    op.drop_index(op.f('ix_pure_internal_org_level'), table_name='pure_internal_org')
    op.create_table('collections_analysis_cited',
    sa.Column('cited_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('cited_abstract_doi', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_publication_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('authored_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('collections_analysis_cited_mvw',
    sa.Column('cited_abstract_scopus_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cited_abstract_doi', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_publication_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('authored_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('scopus_emerald_issns',
    sa.Column('issn_1', sa.VARCHAR(length=50), nullable=False),
    sa.Column('issn_2', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('issn_1', name='sys_c001743719')
    )
    op.create_table('collections_analysis_authored_mvw',
    sa.Column('abstract_scopus_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('doi', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('publication_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('umn_scopus_articles_authors_by_issn',
    sa.Column('issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('article_doi', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('abstract_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True)
    )
    op.create_table('umn_author_citations_temp',
    sa.Column('abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('citation_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issn', sa.VARCHAR(length=4000), nullable=True)
    )
    op.create_table('jsonview_pure_research_output_external_ids',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('scopus_id', sa.VARCHAR(length=150), nullable=True),
    sa.Column('qabo_id', sa.VARCHAR(length=150), nullable=True),
    sa.Column('pmid', sa.VARCHAR(length=150), nullable=True),
    sa.Column('pmcid', sa.VARCHAR(length=150), nullable=True),
    sa.Column('orcid', sa.VARCHAR(length=150), nullable=True)
    )
    op.create_index('idx_pure_research_output_external_ids_uuid', 'jsonview_pure_research_output_external_ids', ['uuid'], unique=False)
    op.create_table('jsonview_pub',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pureid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('title', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('container_title', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('journal_uuid', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('volume', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('pages', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issue', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('citation_total', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('owner_pure_org_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.Column('pure_type', sa.VARCHAR(length=16000), nullable=True),
    sa.Column('pure_subtype', sa.VARCHAR(length=16000), nullable=True),
    sa.Column('issued', oracle.DATE(), nullable=True),
    sa.Column('issued_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issued_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('eissued', oracle.DATE(), nullable=True),
    sa.Column('eissued_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('eissued_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('unissued', oracle.DATE(), nullable=True),
    sa.Column('unissued_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('unissued_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('inprep', oracle.DATE(), nullable=True),
    sa.Column('inprep_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('inprep_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('submitted', oracle.DATE(), nullable=True),
    sa.Column('submitted_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('submitted_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('inpress', oracle.DATE(), nullable=True),
    sa.Column('inpress_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('inpress_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('doi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('doi_openaccess', sa.VARCHAR(length=255), nullable=True),
    sa.Column('qabo_id', sa.VARCHAR(length=150), nullable=True),
    sa.Column('pmid', sa.VARCHAR(length=150), nullable=True),
    sa.Column('pmcid', sa.VARCHAR(length=150), nullable=True),
    sa.Column('orcid', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='pk_jsonview_pub')
    )
    op.create_index('jsonview_pub_scopus_id', 'jsonview_pub', ['scopus_id'], unique=False)
    op.create_index('jsonview_pub_orcid', 'jsonview_pub', ['orcid'], unique=False)
    op.create_index('jsonview_pub_doi', 'jsonview_pub', ['doi'], unique=False)
    op.create_table('umn_authored_abstract_cited_scopus_ids',
    sa.Column('authored_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('cited_abstract_scopus_id', sa.VARCHAR(length=4000), nullable=True)
    )
    op.create_table('jsonview_previous_uuid',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('previous_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('uuid', 'previous_uuid', name='pk_uuid_previous_uuid')
    )
    op.create_table('umn_author_ids',
    sa.Column('authored_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('mrsec_author_list',
    sa.Column('authorid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('scopusid', sa.VARCHAR(length=64), nullable=True)
    )
    op.create_table('jsonview_pure_research_output_pubdates',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('issued', oracle.DATE(), nullable=True),
    sa.Column('issued_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issued_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('eissued', oracle.DATE(), nullable=True),
    sa.Column('eissued_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('eissued_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('unissued', oracle.DATE(), nullable=True),
    sa.Column('unissued_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('unissued_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('inprep', oracle.DATE(), nullable=True),
    sa.Column('inprep_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('inprep_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('submitted', oracle.DATE(), nullable=True),
    sa.Column('submitted_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('submitted_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('inpress', oracle.DATE(), nullable=True),
    sa.Column('inpress_current', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('inpress_precision', oracle.NUMBER(asdecimal=False), nullable=True)
    )
    op.create_index('idx_pure_research_output_pubdates_uuid', 'jsonview_pure_research_output_pubdates', ['uuid'], unique=False)
    op.create_table('jsonview_umn_person_pure_org',
    sa.Column('person_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pure_org_uuid', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('staff_type', sa.VARCHAR(length=16000), nullable=True),
    sa.Column('job_description', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('employed_as', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('start_date', oracle.DATE(), nullable=True),
    sa.Column('end_date', oracle.DATE(), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('pure_person_id', sa.VARCHAR(length=4096), nullable=True)
    )
    op.create_index('idx_jsonview_umn_person_pure_org_pure_person_uuid', 'jsonview_umn_person_pure_org', ['person_uuid'], unique=False)
    op.create_index('idx_jsonview_umn_person_pure_org_pure_org_uuid', 'jsonview_umn_person_pure_org', ['pure_org_uuid'], unique=False)
    op.create_index('idx_jsonview_umn_person_pure_org_pure_org_pure_person_id', 'jsonview_umn_person_pure_org', ['pure_person_id'], unique=False)
    op.create_index('idx_jsonview_umn_person_pure_org_pure_org_emplid', 'jsonview_umn_person_pure_org', ['emplid'], unique=False)
    op.create_table('jsonview_pure_research_output_doi',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('doi_openaccess', sa.VARCHAR(length=255), nullable=True),
    sa.Column('doi', sa.VARCHAR(length=255), nullable=True)
    )
    op.create_index('idx_pure_research_output_doi_uuid', 'jsonview_pure_research_output_doi', ['uuid'], unique=False)
    op.create_index('idx_pure_research_output_doi_doi', 'jsonview_pure_research_output_doi', ['doi'], unique=False)
    op.create_table('pure_json_test',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_test_json_document'),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_json_test')
    )
    op.create_table('jsonview_umn_scopus_ids_3_years',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False)
    )
    op.create_table('collections_analysis_authored',
    sa.Column('abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('doi', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('publication_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('mrsec_irg_2_nodes',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=10), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False)
    )
    op.create_table('pure_json_test_staging',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('inserted', oracle.DATE(), nullable=False),
    sa.Column('json_document', sa.CLOB(), nullable=False),
    sa.Column('updated', oracle.DATE(), nullable=False),
    sa.Column('pure_created', oracle.DATE(), nullable=False),
    sa.Column('pure_modified', oracle.DATE(), nullable=False),
    sa.CheckConstraint('json_document IS JSON', name='ck_pure_json_test_staging_json_document'),
    sa.PrimaryKeyConstraint('uuid', 'pure_modified', name='pk_pure_json_test_staging')
    )
    op.create_table('mrsec_all_nodes',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('pureuuid', sa.VARCHAR(length=64), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('scopusid', sa.VARCHAR(length=36), nullable=True)
    )
    op.create_table('umn_cited_abstract_ids',
    sa.Column('cited_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('cited_abstract_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_doi', sa.VARCHAR(length=4000), nullable=True)
    )
    op.create_table('umn_scopus_articles_authors_by_issn_test',
    sa.Column('issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('abstract_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('mrsec_march_nodes',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('pureuuid', sa.VARCHAR(length=64), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fullname', sa.VARCHAR(length=128), nullable=True),
    sa.Column('scopusid', sa.VARCHAR(length=36), nullable=True)
    )
    op.create_table('jsonview_person_pure_org',
    sa.Column('person_uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('pure_org_uuid', sa.VARCHAR(length=4000), nullable=True)
    )
    op.create_index('idx_jsonview_person_pure_org_person_uuid_org_uuid', 'jsonview_person_pure_org', ['person_uuid', 'pure_org_uuid'], unique=False)
    op.create_table('umn_scopus_cited_articles_authors_by_issn',
    sa.Column('cited_abstract_issn', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_doi', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_year', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('cited_abstract_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('authored_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False)
    )
    op.create_table('mrsec_irg_1_research_outputs',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False)
    )
    op.create_table('mrsec_irg_1_nodes',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=10), nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), nullable=True),
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False)
    )
    op.create_index('mrsec_irg_1_nodes_index2', 'mrsec_irg_1_nodes', ['emplid'], unique=False)
    op.create_index('mrsec_irg_1_nodes_index1', 'mrsec_irg_1_nodes', ['uuid'], unique=False)
    op.create_table('mrsec_march_research_outputs',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False)
    )
    op.create_table('jsonview_pure_person',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('pure_id', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('emplid', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('internet_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('orcid', sa.VARCHAR(length=80), nullable=True),
    sa.Column('hindex', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('scopus_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('pure_modified', oracle.DATE(), nullable=True),
    sa.Column('pure_internal', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='pk_pure_person')
    )
    op.create_index('jsonview_pure_person_scopus_id', 'jsonview_pure_person', ['scopus_id'], unique=False)
    op.create_index('jsonview_pure_person_internet_id', 'jsonview_pure_person', ['internet_id'], unique=False)
    op.create_index('jsonview_pure_person_emplid', 'jsonview_pure_person', ['emplid'], unique=False)
    op.create_table('jsonview_pure_org',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('pure_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('parent_pure_uuid', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('parent_pure_id', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('pure_internal', sa.CHAR(length=1), nullable=True),
    sa.Column('type', sa.VARCHAR(length=16000), nullable=True),
    sa.Column('name_en', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('name_variant_en', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('url', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('pure_modified', oracle.DATE(), nullable=True)
    )
    op.create_index('idx_pure_org_uuid', 'jsonview_pure_org', ['uuid'], unique=False)
    op.create_index('idx_pure_org_pure_id', 'jsonview_pure_org', ['pure_id'], unique=False)
    op.create_table('umn_pure_person_ids',
    sa.Column('emplid', sa.VARCHAR(length=11), nullable=False),
    sa.Column('internet_id', sa.VARCHAR(length=15), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True)
    )
    op.create_table('jsonview_unified_pure_json',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('pure_modified', oracle.DATE(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=31), nullable=True),
    sa.Column('json_document', sa.CLOB(), nullable=True)
    )
    op.create_index('idx_jsonview_unified_pure_json_uuid', 'jsonview_unified_pure_json', ['uuid'], unique=False)
    op.create_index('idx_jsonview_unified_pure_json_source', 'jsonview_unified_pure_json', ['source'], unique=False)
    op.create_table('mrsec_irg_2_research_outputs',
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False)
    )
    op.create_table('jsonview_pub_person',
    sa.Column('pub_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('person_pureid', sa.VARCHAR(length=144), nullable=True),
    sa.Column('person_pure_internal', sa.CHAR(length=1), nullable=True),
    sa.Column('person_uuid', sa.VARCHAR(length=144), nullable=True),
    sa.Column('person_link', sa.VARCHAR(length=600), nullable=True),
    sa.Column('person_role', sa.VARCHAR(length=1020), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=4096), nullable=True),
    sa.Column('person_ordinal', oracle.NUMBER(asdecimal=False), nullable=True)
    )
    op.create_index('idx_pub_person_pub_uuid_person_uuid', 'jsonview_pub_person', ['pub_uuid', 'person_uuid'], unique=False)
    op.create_index('idx_pub_person_pub_person_uuid', 'jsonview_pub_person', ['person_uuid'], unique=False)
    op.create_table('jsonview_umn_dept_pure_org',
    sa.Column('pure_org_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('deptid_descr', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pure_org_id', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('deptid', sa.VARCHAR(length=10), nullable=True),
    sa.Column('deptid_uri', sa.VARCHAR(length=4000), nullable=True)
    )
    op.create_index('idx_jsonview_umn_dept_pure_org_pure_org_uuid', 'jsonview_umn_dept_pure_org', ['pure_org_uuid'], unique=False)
    op.create_index('idx_jsonview_umn_dept_pure_org_pure_org_id', 'jsonview_umn_dept_pure_org', ['pure_org_id'], unique=False)
    op.create_index('idx_jsonview_umn_dept_pure_org_deptid', 'jsonview_umn_dept_pure_org', ['deptid'], unique=False)
    op.create_table('mrsec_all_research_outputs',
    sa.Column('id', oracle.NUMBER(precision=20, scale=0, asdecimal=False), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=64), nullable=True)
    )
    op.create_table('umn_authored_abstract_author_scopus_ids',
    sa.Column('authored_abstract_scopus_id', sa.INTEGER(), nullable=False),
    sa.Column('author_scopus_id', sa.VARCHAR(length=4000), nullable=True)
    )
    op.drop_index(op.f('ix_pure_sync_award_internal_holder_emplid'), table_name='pure_sync_award_internal_holder')
    op.drop_table('pure_sync_award_internal_holder')
    op.drop_table('pure_eligible_graduate_program')
    # ### end Alembic commands ###
