"""Made all new uuids FKs.

Revision ID: 66d69988133c
Revises: f837da07b30f
Create Date: 2017-04-14 09:18:45.649510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '66d69988133c'
down_revision = 'f837da07b30f'
branch_labels = None
depends_on = None


def upgrade():
  op.alter_column(
    'mds_person_instl_email_addr',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_instl_email_addr',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_internet_id',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_internet_id',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_first_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_first_name',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_last_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_last_name',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_middle_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_middle_name',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_name_suffix',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_name_suffix',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_preferred_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_preferred_name',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_primary_empl_rcdno',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_primary_empl_rcdno',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_tenure_flag',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_tenure_flag',
    'mds_person',
    ['uuid'],
    ['uuid']
  )
  op.alter_column(
    'mds_person_tenure_track_flag',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=False
  )
  op.create_foreign_key(
    None,
    'mds_person_tenure_track_flag',
    'mds_person',
    ['uuid'],
    ['uuid']
  )

def downgrade():
  op.drop_constraint(
    None,
    'mds_person_tenure_track_flag',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_tenure_track_flag',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_tenure_flag',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_tenure_flag',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_primary_empl_rcdno',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_primary_empl_rcdno',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_preferred_name',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_preferred_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_name_suffix',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_name_suffix',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_middle_name',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_middle_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_first_name',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_first_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_last_name',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_last_name',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_internet_id',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_internet_id',
    'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
  op.drop_constraint(
    None,
    'mds_person_instl_email_addr',
    type_='foreignkey'
  )
  op.alter_column(
    'mds_person_instl_email_addr', 'uuid',
    existing_type=sa.VARCHAR(length=36),
    nullable=True
  )
