"""Adds PureApiPub, which stores research output json from the Pure API.

Revision ID: a682994747e0
Revises: 7c32ff151649
Create Date: 2018-05-28 14:19:48.047719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'a682994747e0'
down_revision = '7c32ff151649'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pure_api_pub',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('downloaded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )

def downgrade():
    op.drop_table('pure_api_pub')
