"""Expands jobcode_descr to 120 characters.

Revision ID: c4751a4dbc56
Revises: 5ef0b3a6aebf
Create Date: 2021-07-27 08:44:34.094772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'c4751a4dbc56'
down_revision = '5ef0b3a6aebf'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('pure_eligible_affiliate_jobcode', 'jobcode_descr',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('pure_eligible_employee_jobcode', 'jobcode_descr',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('pure_eligible_poi_jobcode', 'jobcode_descr',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('umn_data_error', 'jobcode_descr',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=120),
               existing_nullable=True)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('umn_data_error', 'jobcode_descr',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    op.alter_column('pure_eligible_poi_jobcode', 'jobcode_descr',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    op.alter_column('pure_eligible_employee_jobcode', 'jobcode_descr',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
    op.alter_column('pure_eligible_affiliate_jobcode', 'jobcode_descr',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
