"""Added uuids to remaining tables.

Revision ID: f837da07b30f
Revises: 57028f204264
Create Date: 2017-04-14 08:44:55.739535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f837da07b30f'
down_revision = '57028f204264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mds_person_first_name', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_instl_email_addr', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_internet_id', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_last_name', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_middle_name', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_name_suffix', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_preferred_name', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_primary_empl_rcdno', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_tenure_flag', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('mds_person_tenure_track_flag', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mds_person_tenure_track_flag', 'uuid')
    op.drop_column('mds_person_tenure_flag', 'uuid')
    op.drop_column('mds_person_primary_empl_rcdno', 'uuid')
    op.drop_column('mds_person_preferred_name', 'uuid')
    op.drop_column('mds_person_name_suffix', 'uuid')
    op.drop_column('mds_person_middle_name', 'uuid')
    op.drop_column('mds_person_last_name', 'uuid')
    op.drop_column('mds_person_internet_id', 'uuid')
    op.drop_column('mds_person_instl_email_addr', 'uuid')
    op.drop_column('mds_person_first_name', 'uuid')
    # ### end Alembic commands ###
