-- Source: https://static.helpjuice.com/helpjuice_production/uploads/upload/image/15881/3794630/1716885297829-oracle_person_view_create_statements.sql

-- PERSON DATA AND RELATED VIEWS
CREATE TABLE PERSON_DATA
(
    PERSON_ID varchar(1024) not null,
    FIRST_NAME varchar(1024),
    LAST_NAME varchar(1024) not null,
    DATE_OF_BIRTH date,
    NATIONALITY varchar(1024),
    GENDER varchar(1024) not null,
    EMPLOYEE_START_DATE date,
    SYSTEM_LEAVING_DATE date,
    RETIRAL_DATE date,
    ACADEMIC_PROFESSION_ENTRY date,
    EXPERT number(1,0),
    WILLINGNESS_TO_PHD number(1,0),
    PHD_RESEARCH_PROJECTS clob,
    AFFILIATION_NOTE clob,
    ORCID varchar(20),
    BUILDING varchar(1024),
    CITY varchar(1024),
    COUNTRY varchar(1024),
    POSTAL_CODE varchar(1024),
    ROAD varchar(1024),
    ROOM varchar(1024),
    VISIBILITY varchar(1024),
    USER_ID varchar(1024),
    MANAGED_IN_PURE number(1,0),
    PROFILED number(1,0)
)
;
CREATE TABLE PERSON_IDS
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    VALUE varchar(255) not null
)
;
CREATE TABLE PERSON_NAMES
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    FIRST_NAME varchar(1024),
    LAST_NAME varchar(1024)
)
;
CREATE TABLE PERSON_TITLES
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    VALUE varchar(255)
)
;
CREATE TABLE PERSON_PROFILE_INFORMATION
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    VALUE clob
)
;
CREATE TABLE PERSON_LEAVE_OF_ABSENCE
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    START_DATE date not null,
    END_DATE date
)
;
CREATE TABLE PERSON_DOCUMENTS
(
    ID varchar(1024) not null,
    PERSON_ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    URL varchar(1024) not null,
    PROTOCOL varchar(1024),
    FILE_NAME varchar(1024),
    MIME_TYPE varchar(1024),
    FILE_TITLE varchar(1024),
    VISIBILITY varchar(1024)
)
;
CREATE TABLE PERSON_PHOTOS
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    TYPE varchar(1024) not null,
    VALUE varchar(1024) not null,
    PROTOCOL varchar(255) not null,
    FILE_NAME varchar(1024),
    MIME_TYPE varchar(1024)
)
;
CREATE TABLE PERSON_EDUCATIONS
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    QUALIFICATION varchar(1024),
    FIELD_OF_STUDY varchar(1024),
    QUALIFICATION_STRING varchar(1024),
    FIELD_OF_STUDY_STRING varchar(1024),
    PROJECT_TITLE varchar(1024),
    AWARD_DATE date,
    START_DATE_YEAR number,
    START_DATE_MONTH number,
    START_DATE_DAY number,
    END_DATE_YEAR number,
    END_DATE_MONTH number,
    END_DATE_DAY number,
    ORG_ID varchar(1024),
    ORG_PURE_ID number,
    ORG_SOURCE_ID varchar(1024),
    ORG_CLASSIFIED_IDS_ID varchar(1024),
    ORG_CLASSIFIED_IDS_TYPE varchar(1024),
    EXTERNAL_ORG_ID varchar(1024),
    EXTERNAL_ORG_PURE_ID number,
    EXTERNAL_ORG_SOURCE_ID varchar(1024),
    EXTERNAL_ORG_NAME varchar(1024),
    EXTERNAL_ORG_TYPE varchar(1024),
    EXTERNAL_ORG_COUNTRY varchar(1024)
)
;
CREATE TABLE PERSON_EXTERNAL_POSITIONS
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    APPOINTMENT varchar(1024),
    APPOINTMENT_STRING varchar(1024),
    START_DATE_YEAR number,
    START_DATE_MONTH number,
    START_DATE_DAY number,
    END_DATE_YEAR number,
    END_DATE_MONTH number,
    END_DATE_DAY number,
    EXTERNAL_ORG_ID varchar(1024),
    EXTERNAL_ORG_PURE_ID number,
    EXTERNAL_ORG_SOURCE_ID varchar(1024),
    EXTERNAL_ORG_NAME varchar(1024),
    EXTERNAL_ORG_TYPE varchar(1024),
    EXTERNAL_ORG_COUNTRY varchar(1024)
)
;
CREATE TABLE PERSON_PROF_QUALIFICATIONS
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    QUALIFICATION varchar(1024),
    ABBREVIATED_QUALIFICATION varchar(1024),
    START_DATE_YEAR number,
    START_DATE_MONTH number,
    START_DATE_DAY number,
    END_DATE_YEAR number,
    END_DATE_MONTH number,
    END_DATE_DAY number
)
;
CREATE TABLE PERSON_LINKS
(
    PERSON_ID varchar(1024) not null,
    ID varchar(1024) not null,
    URL varchar(1024) not null,
    TYPE varchar(1024),
    DESCRIPTION varchar(1024)
)
;
CREATE TABLE PERSON_KEYWORDS
(
    PERSON_ID varchar(1024) not null,
    LOGICAL_NAME varchar(1024) not null,
    TYPE varchar(1024),
    FREE_KEYWORD varchar(1024)
)
;
-- PERSON ORGANISATION ASSOCIATION RELATIONS AND RELATED VIEWS
CREATE TABLE STAFF_ORG_RELATION
(
    ID varchar(1024) not null,
    PERSON_ID varchar(1024) not null,
    ORG_ID varchar(1024),
    ORG_PURE_ID number,
    ORG_SOURCE_ID varchar(1024),
    ORG_CLASSIFIED_IDS_ID varchar(1024),
    ORG_CLASSIFIED_IDS_TYPE varchar(1024),
    EMPLOYMENT_TYPE varchar(1024),
    AFFILIATION_ID varchar(30),
    PERIOD_START_DATE date not null,
    PERIOD_END_DATE date,
    PRIMARY_ASSOCIATION number(1,0),
    CONTRACT_TYPE varchar(1024),
    STAFF_TYPE varchar(1024),
    JOB_TITLE varchar(1024),
    JOB_DESCRIPTION varchar(1024),
    FTE number,
    MANAGED_IN_PURE number(1,0)
)
;
CREATE TABLE HONORARY_STAFF_ORG_RELATION
(
    ID varchar(1024) not null,
    PERSON_ID varchar(1024) not null,
    ORG_ID varchar(1024),
    ORG_PURE_ID number,
    ORG_SOURCE_ID varchar(1024),
    ORG_CLASSIFIED_IDS_ID varchar(1024),
    ORG_CLASSIFIED_IDS_TYPE varchar(1024),
    EMPLOYMENT_TYPE varchar(1024),
    AFFILIATION_ID varchar(30),
    PERIOD_START_DATE date not null,
    PERIOD_END_DATE date,
    PRIMARY_ASSOCIATION number(1,0),
    CONTRACT_TYPE varchar(1024),
    STAFF_TYPE varchar(1024),
    JOB_TITLE varchar(1024),
    JOB_DESCRIPTION varchar(1024),
    MANAGED_IN_PURE number(1,0)
)
;
CREATE TABLE VISITING_SCHOLAR_ORG_RELATION
(
    ID varchar(1024) not null,
    PERSON_ID varchar(1024) not null,
    ORG_ID varchar(1024),
    ORG_PURE_ID number,
    ORG_SOURCE_ID varchar(1024),
    ORG_CLASSIFIED_IDS_ID varchar(1024),
    ORG_CLASSIFIED_IDS_TYPE varchar(1024),
    EMPLOYMENT_TYPE varchar(1024),
    AFFILIATION_ID varchar(30),
    PERIOD_START_DATE date not null,
    PERIOD_END_DATE date,
    PRIMARY_ASSOCIATION number(1,0),
    PURPOSE_OF_STAY varchar(512),
    VISITOR_FROM_ID varchar(1024),
    VISITOR_FROM_PURE_ID number,
    VISITOR_FROM_SOURCE_ID varchar(1024),
    VISITOR_FROM_NAME varchar(1024),
    VISITOR_FROM_TYPE varchar(1024),
    VISITOR_FROM_COUNTRY varchar(1024),
    JOB_TITLE varchar(1024),
    JOB_DESCRIPTION varchar(1024),
    MANAGED_IN_PURE number(1,0)
)
;
CREATE TABLE STUDENT_ORG_RELATION
(
    ID varchar(1024) not null,
    PERSON_ID varchar(1024) not null,
    ORG_ID varchar(1024),
    ORG_PURE_ID number,
    ORG_SOURCE_ID varchar(1024),
    ORG_CLASSIFIED_IDS_ID varchar(1024),
    ORG_CLASSIFIED_IDS_TYPE varchar(1024),
    EMPLOYMENT_TYPE varchar(1024),
    AFFILIATION_ID varchar(30),
    PERIOD_START_DATE date not null,
    PERIOD_END_DATE date,
    PRIMARY_ASSOCIATION number(1,0),
    START_YEAR varchar(30),
    STATUS varchar(1024) not null,
    PROGRAMME varchar(512),
    STUDENT_TYPE_DESCRIPTION varchar(1024),
    EXPECTED_STUDY_DURATION number,
    MIN_STUDY_DURATION number,
    MAX_STUDY_DURATION number,
    PROGRAMME_YEAR varchar(65),
    STUDENT_NATIONALITY varchar(1024),
    STUDENT_RESIDENCY_FLAG varchar(1024),
    STUDENT_COUNTRY_OF_DOMICILE varchar(1024),
    AWARD_GAINED varchar(256),
    PROJECT_TITLE varchar(1024),
    AWARD_DATE date,
    INITIAL_SUBMISSION_DATE date,
    EXPECTED_END_DATE date,
    FTE number,
    MANAGED_IN_PURE number(1,0)
)
;
CREATE TABLE ORG_RELATION_ADDRESSES
(
    ID varchar(1024) not null,
    STAFF_RELATION_ID varchar(1024),
    STUDENT_RELATION_ID varchar(1024),
    VISITOR_RELATION_ID varchar(1024),
    HONORARY_RELATION_ID varchar(1024),
    TYPE varchar(1024) not null,
    CITY varchar(1024),
    POSTAL_CODE varchar(1024),
    STREET varchar(1024),
    BUILDING varchar(1024),
    DISPLAY_FORMAT varchar(2048),
    COUNTRY varchar(1024),
    SUBDIVISION varchar(1024),
    GEO_LOCATION_POINT varchar(512),
    GEO_LOCATION_POLYGON clob
)
;
CREATE TABLE ORG_RELATION_PHONE_NUMBERS
(
    ID varchar(1024) not null,
    STAFF_RELATION_ID varchar(1024),
    STUDENT_RELATION_ID varchar(1024),
    VISITOR_RELATION_ID varchar(1024),
    HONORARY_RELATION_ID varchar(1024),
    TYPE varchar(1024) not null,
    VALUE varchar(64) not null
)
;
CREATE TABLE ORG_RELATION_EMAILS
(
    ID varchar(1024) not null,
    STAFF_RELATION_ID varchar(1024),
    STUDENT_RELATION_ID varchar(1024),
    VISITOR_RELATION_ID varchar(1024),
    HONORARY_RELATION_ID varchar(1024),
    TYPE varchar(1024) not null,
    VALUE varchar(255) not null
)
;
CREATE TABLE ORG_RELATION_WEB_ADDRESSES
(
    ID varchar(1024) not null,
    STAFF_RELATION_ID varchar(1024),
    STUDENT_RELATION_ID varchar(1024),
    VISITOR_RELATION_ID varchar(1024),
    HONORARY_RELATION_ID varchar(1024),
    TYPE varchar(1024) not null,
    VALUE varchar(1024)
)
;
CREATE TABLE ORG_RELATION_KEYWORDS
(
    STAFF_RELATION_ID varchar(1024),
    STUDENT_RELATION_ID varchar(1024),
    VISITOR_RELATION_ID varchar(1024),
    HONORARY_RELATION_ID varchar(1024),
    LOGICAL_NAME varchar(1024) not null,
    TYPE varchar(1024) not null
)
;

CREATE TABLE ORG_RELATION_FUNDING_ORGS
(
    ID varchar(1024) not null,
    STUDENT_RELATION_ID varchar(1024) not null,
    ORG_ID varchar(1024),
    ORG_ID_HINT varchar(1024),
    EXT_ORG_ID varchar(1024),
    EXT_ORG_ID_HINT varchar(1024),
    EXT_ORG_NAME varchar(1024),
    EXT_ORG_TYPE varchar(1024),
    EXT_ORG_COUNTRY varchar(1024),
    ACADEMIC_YEAR varchar(20),
    AMOUNT number,
    AMOUNT_CURRENCY varchar(1024),
    COST_CENTRE_CODE varchar(40),
    ANALYSIS_CODE varchar(40),
    PERCENT number,
    FUNDER_TYPE varchar(1024),
    PROJECT_ID varchar(1024),
    PROJECT_ID_HINT varchar(1024)
)
;

-- SUPERVISOR DATA
CREATE TABLE SUPERVISOR_DATA
(
    ID varchar(1024) not null,
    APPRENTICE_ID varchar(1024),
    SUPERVISOR_ID varchar(1024),
    SUPERVISOR_PURE_ID number,
    SUPERVISOR_SOURCE_ID varchar(1024),
    SUPERVISOR_IDS_ID varchar(1024),
    SUPERVISOR_IDS_TYPE varchar(1024),
    SUPERVISOR_ORG_RELATION_ID varchar(1024) not null,
    APPRENTICE_ORG_RELATION_ID varchar(1024) not null,
    SUPERVISION_PERCENTAGE number,
    LEAD_SUPERVISOR number(1,0) not null,
    START_DATE date not null,
    END_DATE date
)
;

-- USER DATA
CREATE TABLE USER_DATA
(
    ID varchar(1024) not null,
    FIRST_NAME varchar(1024),
    LAST_NAME varchar(1024),
    USER_NAME varchar(1024) not null,
    EMAIL varchar(1024) not null
)
;

CREATE INDEX ORG_RELATION_KEYWORDS_STAFF_RELATION_ID_INDEX on ORG_RELATION_KEYWORDS (STAFF_RELATION_ID);
CREATE INDEX ORG_RELATION_KEYWORDS_STUDENT_RELATION_ID_INDEX on ORG_RELATION_KEYWORDS (STUDENT_RELATION_ID);
CREATE INDEX ORG_RELATION_KEYWORDS_VISITOR_RELATION_ID_INDEX on ORG_RELATION_KEYWORDS (VISITOR_RELATION_ID);
CREATE INDEX ORG_RELATION_KEYWORDS_HONORARY_RELATION_ID_INDEX on ORG_RELATION_KEYWORDS (HONORARY_RELATION_ID);
CREATE INDEX ORG_RELATION_WEB_ADDRESSES_ID_INDEX on ORG_RELATION_WEB_ADDRESSES (ID);
CREATE INDEX ORG_RELATION_WEB_ADDRESSES_STAFF_RELATION_ID_INDEX on ORG_RELATION_WEB_ADDRESSES (STAFF_RELATION_ID);
CREATE INDEX ORG_RELATION_WEB_ADDRESSES_STUDENT_RELATION_ID_INDEX on ORG_RELATION_WEB_ADDRESSES (STUDENT_RELATION_ID);
CREATE INDEX ORG_RELATION_WEB_ADDRESSES_VISITOR_RELATION_ID_INDEX on ORG_RELATION_WEB_ADDRESSES (VISITOR_RELATION_ID);
CREATE INDEX ORG_RELATION_WEB_ADDRESSES_HONORARY_RELATION_ID_INDEX on ORG_RELATION_WEB_ADDRESSES (HONORARY_RELATION_ID);
CREATE INDEX ORG_RELATION_EMAILS_ID_INDEX on ORG_RELATION_EMAILS (ID);
CREATE INDEX ORG_RELATION_EMAILS_STAFF_RELATION_ID_INDEX on ORG_RELATION_EMAILS (STAFF_RELATION_ID);
CREATE INDEX ORG_RELATION_EMAILS_STUDENT_RELATION_ID_INDEX on ORG_RELATION_EMAILS (STUDENT_RELATION_ID);
CREATE INDEX ORG_RELATION_EMAILS_VISITOR_RELATION_ID_INDEX on ORG_RELATION_EMAILS (VISITOR_RELATION_ID);
CREATE INDEX ORG_RELATION_EMAILS_HONORARY_RELATION_ID_INDEX on ORG_RELATION_EMAILS (HONORARY_RELATION_ID);
CREATE INDEX ORG_RELATION_PHONE_NUMBERS_ID_INDEX on ORG_RELATION_PHONE_NUMBERS (ID);
CREATE INDEX ORG_RELATION_PHONE_NUMBERS_STAFF_RELATION_ID_INDEX on ORG_RELATION_PHONE_NUMBERS (STAFF_RELATION_ID);
CREATE INDEX ORG_RELATION_PHONE_NUMBERS_STUDENT_RELATION_ID_INDEX on ORG_RELATION_PHONE_NUMBERS (STUDENT_RELATION_ID);
CREATE INDEX ORG_RELATION_PHONE_NUMBERS_VISITOR_RELATION_ID_INDEX on ORG_RELATION_PHONE_NUMBERS (VISITOR_RELATION_ID);
CREATE INDEX ORG_RELATION_PHONE_NUMBERS_HONORARY_RELATION_ID_INDEX on ORG_RELATION_PHONE_NUMBERS (HONORARY_RELATION_ID);
CREATE INDEX ORG_RELATION_ADDRESSES_ID_INDEX on ORG_RELATION_ADDRESSES (ID);
CREATE INDEX ORG_RELATION_ADDRESSES_STAFF_RELATION_ID_INDEX on ORG_RELATION_ADDRESSES (STAFF_RELATION_ID);
CREATE INDEX ORG_RELATION_ADDRESSES_STUDENT_RELATION_ID_INDEX on ORG_RELATION_ADDRESSES (STUDENT_RELATION_ID);
CREATE INDEX ORG_RELATION_ADDRESSES_VISITOR_RELATION_ID_INDEX on ORG_RELATION_ADDRESSES (VISITOR_RELATION_ID);
CREATE INDEX ORG_RELATION_ADDRESSES_HONORARY_RELATION_ID_INDEX on ORG_RELATION_ADDRESSES (HONORARY_RELATION_ID);
CREATE INDEX ORG_RELATION_FUNDING_ORGS_ID_INDEX on ORG_RELATION_FUNDING_ORGS (ID);
CREATE INDEX ORG_RELATION_FUNDING_ORGS_STUDENT_RELATION_ID_INDEX on ORG_RELATION_FUNDING_ORGS (STUDENT_RELATION_ID);
CREATE INDEX STUDENT_ORG_RELATION_PERSON_ID_INDEX on STUDENT_ORG_RELATION (PERSON_ID);
CREATE INDEX STUDENT_ORG_RELATION_ID_INDEX on STUDENT_ORG_RELATION (ID);
CREATE INDEX VISITING_SCHOLAR_ORG_RELATION_PERSON_ID_INDEX on VISITING_SCHOLAR_ORG_RELATION (PERSON_ID);
CREATE INDEX VISITING_SCHOLAR_ORG_RELATION_ID_INDEX on VISITING_SCHOLAR_ORG_RELATION (ID);
CREATE INDEX HONORARY_STAFF_ORG_RELATION_PERSON_ID_INDEX on HONORARY_STAFF_ORG_RELATION (PERSON_ID);
CREATE INDEX HONORARY_STAFF_ORG_RELATION_ID_INDEX on HONORARY_STAFF_ORG_RELATION (ID);
CREATE INDEX STAFF_ORG_RELATION_PERSON_ID_INDEX on STAFF_ORG_RELATION (PERSON_ID);
CREATE INDEX STAFF_ORG_RELATION_ID_INDEX on STAFF_ORG_RELATION (ID);
CREATE INDEX PERSON_KEYWORDS_PERSON_ID_INDEX on PERSON_KEYWORDS (PERSON_ID);
CREATE INDEX PERSON_LINKS_PERSON_ID_INDEX on PERSON_LINKS (PERSON_ID);
CREATE INDEX PERSON_LINKS_ID_INDEX on PERSON_LINKS (ID);
CREATE INDEX PERSON_PROF_QUALIFICATIONS_PERSON_ID_INDEX on PERSON_PROF_QUALIFICATIONS (PERSON_ID);
CREATE INDEX PERSON_PROF_QUALIFICATIONS_ID_INDEX on PERSON_PROF_QUALIFICATIONS (ID);
CREATE INDEX PERSON_EXTERNAL_POSITIONS_PERSON_ID_INDEX on PERSON_EXTERNAL_POSITIONS (PERSON_ID);
CREATE INDEX PERSON_EXTERNAL_POSITIONS_ID_INDEX on PERSON_EXTERNAL_POSITIONS (ID);
CREATE INDEX PERSON_EDUCATIONS_PERSON_ID_INDEX on PERSON_EDUCATIONS (PERSON_ID);
CREATE INDEX PERSON_EDUCATIONS_ID_INDEX on PERSON_EDUCATIONS (ID);
CREATE INDEX PERSON_DOCUMENTS_PERSON_ID_INDEX on PERSON_DOCUMENTS (PERSON_ID);
CREATE INDEX PERSON_DOCUMENTS_ID_INDEX on PERSON_DOCUMENTS (ID);
CREATE INDEX PERSON_PHOTOS_PERSON_ID_INDEX on PERSON_PHOTOS (PERSON_ID);
CREATE INDEX PERSON_PHOTOS_ID_INDEX on PERSON_PHOTOS (ID);
CREATE INDEX PERSON_LEAVE_OF_ABSENCE_PERSON_ID_INDEX on PERSON_LEAVE_OF_ABSENCE (PERSON_ID);
CREATE INDEX PERSON_LEAVE_OF_ABSENCE_ID_INDEX on PERSON_LEAVE_OF_ABSENCE (ID);
CREATE INDEX PERSON_PROFILE_INFORMATION_PERSON_ID_INDEX on PERSON_PROFILE_INFORMATION (PERSON_ID);
CREATE INDEX PERSON_PROFILE_INFORMATION_ID_INDEX on PERSON_PROFILE_INFORMATION (ID);
CREATE INDEX PERSON_TITLES_PERSON_ID_INDEX on PERSON_TITLES (PERSON_ID);
CREATE INDEX PERSON_TITLES_ID_INDEX on PERSON_TITLES (ID);
CREATE INDEX PERSON_NAMES_PERSON_ID_INDEX on PERSON_NAMES (PERSON_ID);
CREATE INDEX PERSON_NAMES_ID_INDEX on PERSON_NAMES (ID);
CREATE INDEX PERSON_IDS_PERSON_ID_INDEX on PERSON_IDS (PERSON_ID);
CREATE INDEX PERSON_IDS_ID_INDEX on PERSON_IDS (ID);
CREATE INDEX PERSON_DATA_PERSON_ID_INDEX on PERSON_DATA (PERSON_ID);
